### ISSUE TITLE
baseDir argument

### ISSUE THREAD

**Issue by sh0rez** [sh0rez/tanka#4]
Currently, the `baseDir` is evaluated against the current `pwd`.
To simplify scripts, it should be possible to directly specify the environment on the CLI:

```
tk ACTION default/foo
```

or as an alternative 
```
tk ACTION environments/default/foo
```

While the first option is shorter, the second one is more general, as the argument is an actually valid path on the local file system. This integrates better with the current approach of not enforcing a directory structure, apart from the presence of `main.jsonnet` and `jsonnetfile.json`

**Comment by gouthamve** [comment]
But we are enforcing directory structure, with the existence of `lib` and `vendor` no?

**Comment by sh0rez** [comment]
No, they are only at the `JPATH`. If they exist, they are taken into consideration, if not then not

**Comment by gouthamve** [comment]
I don't have a lot of opinions with this tbh. Lets keep `tk ACTION environments/default/foo` just for the autocomplete purposes.
